### ISSUE TITLE
Why I get the error when I am running the optimize.py code?

### ISSUE THREAD

**Issue by LiuZhe6** [amanrajdce/struct2depth_pub#2]
@amanrajdce Hi,I am very sorry to disturb you.
I have successfully executed the inference code. I want to execute the optimize code but I got the error : ValueError: ('Convolution not supported for input with rank', None)

I still did not understand with the these items which are "data_dir ", "triplet_list_file" and "triplet_list_file_remains". Is this optimize code can not deal with my own data?

This is my command:
prediction_dir="/media/alfred/Linux/dataset/video_to_image/images_output_mini"
model_ckpt="model/struct2depth_model_cityscapes/model-154688"
handle_motion="false"
size_constraint_weight="0" # This must be zero when not handling motion.

data_dir="/media/alfred/Linux/dataset/video_to_image/"       # my own dataset path
triplet_list_file="$data_dir/test_files_cityscapes_triplets.txt"   
triplet_list_file_remains="$data_dir/test_files_cityscapes_triplets_remains.txt"
ft_name="my_data"

python optimize.py \
  --logtostderr \
  --output_dir $prediction_dir \
  --data_dir $data_dir \
  --triplet_list_file $triplet_list_file \
  --triplet_list_file_remains $triplet_list_file_remains \
  --ft_name $ft_name \
  --model_ckpt $model_ckpt \
  --file_extension jpg \
  --handle_motion $handle_motion \
  --size_constraint_weight $size_constraint_weight

the triplet_list_file is like:
data_path 001 ouput_path
data_path 002 output_path

What should I do next? Thank you !

**Comment by amanrajdce** [comment]
@LiuZhe6  I wasn't able to use run optimize.py successfully. These issues might help.
[#7410](https://github.com/tensorflow/models/issues/7410)
[#6173](https://github.com/tensorflow/models/issues/6173)
[#6302](https://github.com/tensorflow/models/issues/6302)
